plugins {
    id 'architectury-plugin' version '3.4.164'
    id 'dev.architectury.loom' version '1.7.435' apply false
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
}
architectury { minecraft = project.minecraft_version }
allprojects {
    group = rootProject.mod_group_id
    version = rootProject.mod_version
}
subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'java-library'
    base { archivesName = "energycontrol-${project.name}" }
    repositories {
        mavenCentral()
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.neoforged.net/releases/' }
    }
    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()
    }
    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        withSourcesJar()
    }
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }
    tasks.withType(AbstractArchiveTask).configureEach {
        preserveFileTimestamps = false
        reproducibleFileOrder = true
    }
    tasks.withType(Jar).configureEach { from(rootProject.file('LICENSE')) }
    processResources {
        inputs.property 'version', project.version
        filesMatching(['fabric.mod.json', 'META-INF/neoforge.mods.toml']) {
            expand version: project.version
        }
    }
}
