# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
## Mod Properties
mod_id=energycontrol
mod_name=Energy Control
mod_license=GNU General Public License v3.0
mod_version=1.20.1-0.3.0
mod_group_id=com.zuxelus.energycontrol
mod_authors=Zuxelus
mod_description=Energy Control is a remastered version of original Nuclear Control, an Industrial Craft 2 addon that allows you to build efficient monitoring and notification system for your energy flow.
