org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=4
minecraft_version=1.21.1
mod_version=1.21.1-0.1.0-port-preview
mod_group_id=com.zuxelus.energycontrol
architectury_version=13.0.8
fabric_loader_version=0.16.14
fabric_api_version=0.116.6+1.21.1
neoforge_version=21.1.209
enabled_platforms=fabric,neoforge
