# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=1.16.5
	yarn_mappings=1.16.5+build.10
	loader_version=0.19.5
	loom_version=1.18-SNAPSHOT

# Mod Properties
	version = 1.16.5-0.3.2
	group = com.zuxelus.energycontrol
	mod_id = energycontrol
	loader_name = fabric

# Dependencies
	fabric_api_version=0.42.0+1.16
	cloth_version=4.17.132
	modmenu_version=1.16.23
	rei_version=5.13.734
	energy_version=0.1.1
